### PR TITLE
App with Redirects to gpc-browsers

### PR DESCRIPTION
**Pull request by n-aggarwal**
Me and Wesley have added buttons and instructions on downloading gpc-browser (brave and duck-duck go). We have not added a button for other gpc-browser since we thought it would make the UI more crowded and reduce usability.

### CODE REVIEW

**Comment by kasnder** [comment]
Thanks, works for me. I feel like the 'why' isn't getting super clear yet. What is GPC? What does it do? Why does it matter for end-users? Why change the browser? Would be important to address all of these questions in the app.

**Review by kasnder — CHANGES_REQUESTED** [review]
Thanks, works for me. I feel like the 'why?' isn't getting super clear yet. What is GPC? What does it do? Why does it matter for end-users? Why change the browser? Would be important to address all of these questions in the app.

**Comment by n-aggarwal** [comment]
Thanks for the feedback. 

Me and Wesley were trying to keep it as short as possible to increase usability and not bog down the user with too much so that it doesn't feel like they have to read a privacy policy. Unfortunately that seems to leave more questions than answers. Would it be better if we created a short description on the main page, something along the following lines:
"Please download one of the browsers below that have built in ad-tracking protection." 

And then add a "learn more" link where we explain a bit more in detail about how the browsers do that and what GPC is, and all the other questions.

Would this be better or do we want to keep it to 1 page.

**Comment by SebastianZimmeck** [comment]
[Figure 1B has](https://sebastianzimmeck.de/zimmeckEtAlGPC2023.pdf) a user-tested explanation of GPC. Maybe, along those lines?

**Comment by SebastianZimmeck** [comment]
Feel free to merge, @n-aggarwal.

**Pull request merged**
