### PR TITLE
Add HAR output to network traffic analysis

### PR DESCRIPTION
**Pull request by kasnder**
HAR scripts are easier to analyse. Additionally, it's nice to keep track of requests that were tried to be initiated but failed, due to certificate pinning or other reasons. The attached script provides a solution. You can run it like this, by appending to the `mitmproxy` call: `-s ./har_dump.py --set hardump=./$appId.zhar` It should be possible to run the script, too, after having already recorded network traffic.

### CODE REVIEW

**Comment by kasnder** [comment]
We'd need to integrate this script with the existing analysis script in #68

**Comment by kasnder** [comment]
This should be merged after #80 is merged.

**Comment by SebastianZimmeck** [comment]
@n-aggarwal, can you review (and merge)?

**Comment by kasnder** [comment]
I've now integrated the HAR script into the current workflow. I haven't tested that yet. Files are directly stored as `.har` and not the compressed `*.zhar`, for simplicity.

**Review by n-aggarwal — APPROVED** [review]

**Pull request merged**
